apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - 0000-buildconfig.yaml
  - 1000-driver-container.yaml
  - 1100-lustre-csi-secret.yaml
  - 2000-lustre-csi-driver.yaml
  name: lustre-client
namespace: lustre-client
