apiVersion: sro.openshift.io/v1beta1
kind: SpecialResource
metadata:
  name: lustre-aws-fsx
spec:
  chart:
    name: lustre-aws-fsx
    version: 0.0.1
    repository:
      name: lustre-aws-specialresource
      url: https://openshift-psap.github.io/lustre-aws-specialresource/
      insecure_skip_tls_verify: true
  namespace: lustre-aws-fsx
  set:
    aws_key_id: "AWS_ACCESS_KEY_ID"
    aws_access_key: "AWS_SECRET_ACCESS_KEY"
    buildArgs:
    - name: "KMODVER"
      value: "SRO"
    kind: Values
    apiVersion: sro.openshift.io/v1beta1
  driverContainer:
    source:
      git:
        ref: "master"
        uri: "https://github.com/openshift-psap/kvc-lustre-client.git"

