apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - 0000-buildconfig.yaml
  - 1000-driver-container.yaml
  - 2000-secret.yaml
  - 3000-csi-controller.yaml
  - 3000-csi-node.yaml
  name: lustre-client
namespace: lustre-client
